### ISSUE TITLE
Quest icons and sparkle effects

### ISSUE THREAD

**Issue by Emzigma** [ImTheCactus/Crow-Get-It-Game#16]
Describe the bug: Quest icons and sparkle effects do not appear and disappear inline with the activation and deactivation of quests.
Version: Crow Get It 3.5 version 0.2.0 *(To be updated on)
Steps to reproduce the behaviour: (In game) Talk to an NPC to initiate a quest and see that the icons are consistently there.
Expected behaviour: The icons should initially be hidden and only appear when the quests are activated.
Desktop system details: OS: Windows10

**Comment by Emzigma** [comment]
As a team, it has been decided that this will be a focus after the Perth Games Festival (PGF).

In the mean time, icons and effects have been removed from the game scene in hopes of not confusing the players.

**Comment by OceanNogg** [comment]
icons and sparkles have been reimported to the scene and linked up to the yarn spinner script so that the quest icons disappear once the quest has been received and the sparkles only appear once the quest has been accepted. I have left the sparkles off the Skarcrow quest items to add some challenge to the final quest.

**Comment by Emzigma** [comment]
Upon recent testing, it was found that the flower's sparkle sprite does not disappear upon the quest item's collection and for this reason, I am re-opening this issue.

**Comment by Emzigma** [comment]
Additionally, there is a very similar issue happening with the dialogue images for Queenie and Bubbles in which their profile pictures don't disappear after the dialogue finishes.

**Comment by OceanNogg** [comment]
this issue has been resolved had to relink some code components

**Comment by OceanNogg** [comment]
this issue has been resolved had to relink some code components
