### ISSUE TITLE
Quest book opening and refuses to close

### ISSUE THREAD

**Issue by Emzigma** [ImTheCactus/Crow-Get-It-Game#2]
**Describe the bug:** As the bug name suggests, the quest books opens and refuses to close.
**Version:** Crow Get It 3.5 version 0.2.0 *(To be updated on)
**Steps to reproduce the behaviour:** This bug occurs when the player interacts with Mush and are about to collect to the peach. Before the player even has a chance to jump up on their dwelling the quest book opens and the designated key (tab) doesn't work to close it. Once opened, the player can no longer interact with Mush or objects. In addition, the quest book obscures the screen as it appears rather large.
**Expected behaviour:** The quest book should only open and close when the player presses the tab key. The interactions with Mush and the peach or any other NPCs or quest items should not open or close the quest book.
**Desktop system details:** OS: Windows10

**Comment by Emzigma** [comment]
In the meantime, the team has agreed to disable the quest book before the Perth Games Festival (PGF) in hopes of resolving the issue there-after.

**Comment by OceanNogg** [comment]
quest book opening has been solved needed to turn of the button click functions left over from the test scean
