### ISSUE TITLE
Fall Zone for Cave Parkour

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#36]
Fall zone to teleport player back to the beginning of the cave parkour instead of the beginning of the river parkour.

**Comment by Emzigma** [comment]
Issue is resolved!

Visual evidence:
![Evidence](https://github.com/ImTheCactus/Crow-Get-It-Game/assets/128340411/22543e43-626f-48f7-bd19-2abe5d78a855)

As you can see, I've added a thin box collider so Cawson's head can no longer go under the water in the cave and therefore doesn't need unnecessarily need a teleport script.
