### ISSUE TITLE
Cave Parkour Checkpoint

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#39]
Description: Players would like there to be a checkpoint at either the half-way point or two-thirds into the cave parkour.
How it would work: If the player collides with an invisible trigger set below the mushrooms, then teleport the player to a set point. This set point would be either half-way or two-thirds into the cave parkour.
Type of feature: Technical feature.

**Comment by Emzigma** [comment]
Issue is resolved!

Visual evidence:
![image](https://github.com/ImTheCactus/Crow-Get-It-Game/assets/128340411/0a07cb71-c06a-4299-ab62-15e444cbb43a)

As you can see, there is now a large, thin trigger that aligns with the undersides of the parkour mushrooms and will teleport the player to the position of the gizmo. This system is essentially the same as the one utilised for the water parkour reset. I have also play-tested it any ensured that it can't be triggered from the underside.
