### ISSUE TITLE
Player Locked in Place During Dialogue

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#40]

**Comment by jacinta42** [comment]
Add the function to lock the player in place while they are talking to an NPC. Player has the ability to walk away during dialogue and dialogue doesn't close.

Locking the player in place will mean that players wont have the ability option to walk away until the interaction has finished eliminating the issue.

**Comment by OceanNogg** [comment]
![image](https://github.com/ImTheCactus/Crow-Get-It-Game/assets/127952964/493874c0-989b-4153-ad51-b1c979fa77e5)
ran into a bug with the first import with the player sinking straight through the floor investigating alternate ways to do it to potentially fix this.

**Comment by OceanNogg** [comment]
was fixed but is bugged again player falling through the floor still

**Comment by OceanNogg** [comment]
the issue has been fixed and implemented fully in all dialogue interactions

Uploading 2023-11-10 19-20-33.mp4…
