### ISSUE TITLE
Increase Bubbles Interact Radius

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#42]
This is so that players can talk to bubbles from the land

**Comment by Emzigma** [comment]
Issue is resolved!

Visual Evidence:
![image](https://github.com/ImTheCactus/Crow-Get-It-Game/assets/128340411/bc90e289-f080-42a7-b8d2-694852b4a9c9)

As you can see, the dialogue radius has been increased so that the player can now talk to Bubbles from the land.
