### ISSUE TITLE
Flying

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#44]

**Comment by jacinta42** [comment]
Players have requested the ability to fly.

This is a very low priority feature as flying has been considered when building the game however with time constraints and skill levels this was not achievable within the given project timeline. We as a team would like to include a cutscene to show why the player cannot fly and we may be able to consider flying in the future if we continue to make progress on crow get it.

Technical feature request

**Comment by Emzigma** [comment]
As a team we've agreed not to implement this feature as it would break various game mechanics like the parkour.
